### ISSUE TITLE
New user email verification email not being sent

### ISSUE THREAD

**Issue by andreas-ateles** [scandipwa/customer-graph-ql#4]
New user email verification email not being sent when the setting for it is enabled in Magento admin.

Additionally in frontend the new user gets a login error when registering (as the registration FE code tries to login at the end of the registration while the account is not yet confirmed). But this is more related to the frontend repo, so maybe it should have a separate bug?

**Comment by andreas-ateles** [comment]
While testing again, the email is delivered, so closing this. But there are other issues signup processes (during it login and adding addresses fails) with this setting on.

**Comment by alfredsgenkins** [comment]
Could you clarify: with which setting on does the address addition fails? :o Never encountered this problem!

**Comment by andreas-ateles** [comment]
The setting Customers -> Customer Configuration -> Require Emails Confirmation: Yes

It requires the user to confirm their email address when registering, before they can login.
