### ISSUE TITLE
Internal error creating a new account

### ISSUE THREAD

**Issue by VladislavSW** [scandipwa/customer-graph-ql#9]
**Describe the bug**
Creating a new account produces an internal error, and a customer is not redirected to the dashboard page, so it is not clear from the UX perspective if the account was actually created.

Note: the account is created, and it is possible to log in afterward using the credentials that were used during account creation but the same internal error will be shown.

GQL request:
```
query: "query  {customer{ created_at, confirmation_required, group_id, prefix, firstname, middlename, lastname, suffix, email, default_billing, default_shipping, dob, taxvat, id, is_subscribed, addresses{ id, customer_id, country_id, street, telephone, postcode, city, firstname, lastname, middlename, prefix, suffix, default_shipping, default_billing, region{ region_code, region, region_id } } }}"
variables: {}
```

GQL response:
`{"errors":[{"debugMessage":"The website with id 9 that was requested wasn't found. Verify the website and try again.","message":"Internal server error","category":"internal","locations":[{"line":1,"column":9}],"path":["customer"]}],"data":{"customer":null}}`

**To Reproduce**
1. Create multiple stores on the same website. 
2. Change the default store view to the store that differs from the website ID, and make sure that there are no website IDs that are equal to the store ID that you've set as the default one. This could be done via Magento env.php using MAGE_RUN_MODE and MAGE_RUN_CODE. 
3. Try to create a new customer account.

**Expected behavior**
The customer is created, redirected to the dashboard page and a successful message is displayed.

**Desktop (please complete the following information):**
 - OS: any compatible
 - Browser any compatible
 - Version any compatible

**Smartphone (please complete the following information):**
 - Device: any compatible
 - OS: any compatible
 - Browser any compatible
 - Version any compatible

**Additional context**
The issue comes from this file: `ScandiPWA\CustomerGraphQl\Model\Customer\ExtractCustomerData`

In the _execute_ method:
```
$isConfirmationRequired =  $this->scopeConfig->isSetFlag(
            AccountConfirmation::XML_PATH_IS_CONFIRM,
            ScopeInterface::SCOPE_WEBSITES,
            $customer->getStoreId()
        );
```
The scope is set to `'websites'` when the argument is the store id instead of the website id.
The issue could be fixed by changing the  `$customer->getStoreId()` to `$customer->getWebsiteId()` in the code above.

**Comment by RoboLV** [comment]
Hey, same bug.

**Comment by alfredsgenkins** [comment]
https://github.com/scandipwa/customer-graph-ql/releases/tag/2.2.2 release with patch by @RoboLV claims to fix the issue :)
